export type ExecutedFunction = {
  id: string;
  name: string;
  description: string;
  parentID: string;
  input: any;
  output: any;
  startTime: number;
  endTime: number;
  totalTime: number;
  error?: string;
  stackTrace?: string[];
  executedSuccessfully: boolean;
  traceID: string;
  environmentName: string;
  moduleName: string;
  fileName: string;
  executionContext: Record<string, any>;
  executionID: string;
  children?: ExecutedFunction[];
};
